services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ems
    networks:
      - my-network

  app:
    image: ems-app1
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge